___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
print('List before append: ',my_list)
my_list.append(4)
print('List after append:', my_list)

List before append:  [1, 2, 3]
List after append: [1, 2, 3, 4]


In [4]:
one_d_array = np.array(my_list) # Conver a list to an array
one_d_array.ndim # ndim--> Helps to check the # of dimensions of the array.

1

In [ ]:
# my_gen_list = [1,2,3,4,'a','b','v','j']
#arr = np.array(my_gen_list)
#A list having characters can also be converted to numpy array but mathematical operations are not possible.

In [ ]:
#print(arr/2)

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # 2d list
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr2 = np.array(my_matrix) # Convert a 2d list to a numpy array which inturn behaves like a matrix

In [ ]:
arr2.ndim

2

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
list0d = 5
arr0d = np.array(list0d)
arr0d.ndim

0

In [6]:
list1d = [1,2,3,4]
arr1d = np.array(list1d)
arr1d.ndim

1

In [7]:
list2d = [[1,2,3,4]]
arr2d = np.array(list2d)
arr2d.ndim

2

In [8]:
list3d = [[[1,2,3,4]]]
arr3d = np.array(list3d)
arr3d.ndim

3

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [10]:

for i in range(1,10):
  print(i) # the value asked for , last value is excluded


1
2
3
4
5
6
7
8
9


In [ ]:
np.arange(0,10) # arange is creating a numpy array within the defined range.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2) # Range 0 to 11 with step 2.

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [19]:
np.zeros((2,4,3)) # level, row, col,

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.zeros((5,5)) # Create a 2d array with 5 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [26]:
np.linspace(0,100,101) # by defauly linespace prints 50 equally spaced values between a range.
# In linespace both the start and end number is inclusive.

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

In [ ]:
np.linspace(0,100,11) # Return 10 numbers evenly spaced between 0 to 100.
# By Default linespace returns 50 evenly spaced numbers.

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [ ]:
np.eye(4) # Diagonal Matrix.

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [30]:
np.random.rand(10) # Randomly generate 10 numbers in a 1d array, in the range 0 to 1

array([0.79356682, 0.85125169, 0.00322775, 0.21778282, 0.76474523,
       0.28746075, 0.24211772, 0.33403734, 0.61468035, 0.34571474])

In [ ]:
np.random.rand(5,5) # Randomly generate a 2d Matrix of shape 5*5 and the number is anything between 0 and 1.

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

In [33]:
np.random.rand(5,5,5)

array([[[0.50767038, 0.95846963, 0.04021179, 0.48793405, 0.65729105],
        [0.18685979, 0.00561984, 0.77100214, 0.77960212, 0.90819413],
        [0.3886996 , 0.57763494, 0.46068181, 0.61938106, 0.18351308],
        [0.90497973, 0.61225488, 0.94019338, 0.03838983, 0.58740778],
        [0.73042378, 0.74834491, 0.76372795, 0.83063061, 0.72659929]],

       [[0.8252982 , 0.73787412, 0.00668225, 0.41649588, 0.11033766],
        [0.17617234, 0.34436531, 0.13793553, 0.77171159, 0.04252799],
        [0.18631997, 0.80544392, 0.33444385, 0.03447383, 0.81452158],
        [0.8525555 , 0.03321366, 0.96869094, 0.74114576, 0.63897255],
        [0.08620618, 0.08116827, 0.87431162, 0.90314561, 0.46784243]],

       [[0.52942679, 0.17717079, 0.26524552, 0.2746845 , 0.71629423],
        [0.76472335, 0.79610333, 0.31354627, 0.28069489, 0.25695134],
        [0.58409514, 0.26529112, 0.59797547, 0.60336053, 0.09514484],
        [0.43442416, 0.08040982, 0.59890371, 0.28531041, 0.806489  ],
        [0.44838

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [31]:
rand_n_samples = np.random.randn(1000)


In [32]:
print(rand_n_samples.mean()) # Close to 0
print(rand_n_samples.std()) # STD close to 1.
print(min(rand_n_samples))
print(max(rand_n_samples))

0.03569010791930929
0.9851935011907044
-3.147778475778418
2.9448083706187496


In [ ]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [39]:
np.random.randint(90,100) # 1 random number between 1 to 100


90

In [53]:
np.random.randint(-100,0) # Single argument in randint means the upper limit(exclusive)

-25

In [54]:
np.random.randint(1,100,5) # NO. OF VALUES TO BE PRINTED BETWEEN 1 TO 100

array([27,  8, 58,  5,  1])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [55]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr

array([28, 47,  0, 48, 31, 44, 13, 15, 17,  1])

In [59]:
arr.shape

(25,)

## Reshape
Returns an array containing the same data with a new shape.

In [67]:
arr4d = arr.reshape(1,1,5,5) # Its a 1 level 2 D array

In [68]:
arr4d.ndim

4

In [69]:
arr4d.shape

(1, 1, 5, 5)

In [76]:
arr4d.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
arr1d = arr4d.reshape(25)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
arr1d.ndim

1

In [75]:
arr1d.shape

(25,)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax() # arg means index. argmax() -> index for maximum value

4

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#LinSpace Explanation
np.linspace(1,2) # 50 values from start to end all inclusive- equi spaced.

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
np.linspace(1,2,10) # 10 values from start to end all inclusive

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [79]:
np.linspace(1,100,99)

array([  1.        ,   2.01020408,   3.02040816,   4.03061224,
         5.04081633,   6.05102041,   7.06122449,   8.07142857,
         9.08163265,  10.09183673,  11.10204082,  12.1122449 ,
        13.12244898,  14.13265306,  15.14285714,  16.15306122,
        17.16326531,  18.17346939,  19.18367347,  20.19387755,
        21.20408163,  22.21428571,  23.2244898 ,  24.23469388,
        25.24489796,  26.25510204,  27.26530612,  28.2755102 ,
        29.28571429,  30.29591837,  31.30612245,  32.31632653,
        33.32653061,  34.33673469,  35.34693878,  36.35714286,
        37.36734694,  38.37755102,  39.3877551 ,  40.39795918,
        41.40816327,  42.41836735,  43.42857143,  44.43877551,
        45.44897959,  46.45918367,  47.46938776,  48.47959184,
        49.48979592,  50.5       ,  51.51020408,  52.52040816,
        53.53061224,  54.54081633,  55.55102041,  56.56122449,
        57.57142857,  58.58163265,  59.59183673,  60.60204082,
        61.6122449 ,  62.62244898,  63.63265306,  64.64

In [ ]:
# Explanation or reshape
list1 = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(list1)
print(arr)
print(arr.ndim)
print(arr.shape)
#10,1 or 1,10 --> 2 dim'
print(arr.reshape(10,1))
print(arr.reshape(1,10))

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [ ]:
#Compare type and dtype
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr.dtype)

int64


In [ ]:
list2 = [1,2,3,4,5,6,7, 'p','jaehfhaegfyagfgaefrgbagjgw',1.0]
np.array(list2).dtype


dtype('<U32')

In [ ]:
list2 = [1,2,3,4,5,6,7, 1.0]
print(np.array(list2))
print(np.array(list2).dtype)


[1. 2. 3. 4. 5. 6. 7. 1.]
float64


In [ ]:
list2 = [1,2,3,4,5,6,7, 1.0,'ejahahed']
print(np.array(list2))
print(np.array(list2).dtype)


['1' '2' '3' '4' '5' '6' '7' '1.0' 'ejahahed']
<U32


# Great Job!